// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MeshStream.proto
#ifndef GRPC_MeshStream_2eproto__INCLUDED
#define GRPC_MeshStream_2eproto__INCLUDED

#include "MeshStream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class MeshStream final {
 public:
  static constexpr char const* service_full_name() {
    return "MeshStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // checks if mesh exist
    virtual ::grpc::Status ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::ValidationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>> AsyncValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>>(AsyncValidateMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>> PrepareAsyncValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>>(PrepareAsyncValidateMeshRaw(context, request, cq));
    }
    // Loads an item
    virtual ::grpc::Status StreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::MeshReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>> AsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>>(AsyncStreamMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>> PrepareAsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>>(PrepareAsyncStreamMeshRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // checks if mesh exist
      virtual void ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest* request, ::ValidationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest* request, ::ValidationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Loads an item
      virtual void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::MeshReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::MeshReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>* AsyncValidateMeshRaw(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ValidationReply>* PrepareAsyncValidateMeshRaw(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>* AsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MeshReply>* PrepareAsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::ValidationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ValidationReply>> AsyncValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ValidationReply>>(AsyncValidateMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ValidationReply>> PrepareAsyncValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ValidationReply>>(PrepareAsyncValidateMeshRaw(context, request, cq));
    }
    ::grpc::Status StreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::MeshReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MeshReply>> AsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MeshReply>>(AsyncStreamMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MeshReply>> PrepareAsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MeshReply>>(PrepareAsyncStreamMeshRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest* request, ::ValidationReply* response, std::function<void(::grpc::Status)>) override;
      void ValidateMesh(::grpc::ClientContext* context, const ::ValidationRequest* request, ::ValidationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::MeshReply* response, std::function<void(::grpc::Status)>) override;
      void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::MeshReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ValidationReply>* AsyncValidateMeshRaw(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ValidationReply>* PrepareAsyncValidateMeshRaw(::grpc::ClientContext* context, const ::ValidationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MeshReply>* AsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MeshReply>* PrepareAsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ValidateMesh_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamMesh_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // checks if mesh exist
    virtual ::grpc::Status ValidateMesh(::grpc::ServerContext* context, const ::ValidationRequest* request, ::ValidationReply* response);
    // Loads an item
    virtual ::grpc::Status StreamMesh(::grpc::ServerContext* context, const ::MeshRequest* request, ::MeshReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateMesh(::grpc::ServerContext* context, ::ValidationRequest* request, ::grpc::ServerAsyncResponseWriter< ::ValidationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamMesh() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMesh(::grpc::ServerContext* context, ::MeshRequest* request, ::grpc::ServerAsyncResponseWriter< ::MeshReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ValidateMesh<WithAsyncMethod_StreamMesh<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ValidationRequest, ::ValidationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ValidationRequest* request, ::ValidationReply* response) { return this->ValidateMesh(context, request, response); }));}
    void SetMessageAllocatorFor_ValidateMesh(
        ::grpc::MessageAllocator< ::ValidationRequest, ::ValidationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ValidationRequest, ::ValidationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamMesh() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::MeshRequest, ::MeshReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::MeshRequest* request, ::MeshReply* response) { return this->StreamMesh(context, request, response); }));}
    void SetMessageAllocatorFor_StreamMesh(
        ::grpc::MessageAllocator< ::MeshRequest, ::MeshReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MeshRequest, ::MeshReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ValidateMesh<WithCallbackMethod_StreamMesh<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamMesh() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateMesh(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamMesh() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMesh(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ValidateMesh(context, request, response); }));
    }
    ~WithRawCallbackMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamMesh() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamMesh(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ValidateMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ValidateMesh() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ValidationRequest, ::ValidationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ValidationRequest, ::ValidationReply>* streamer) {
                       return this->StreamedValidateMesh(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ValidateMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ValidateMesh(::grpc::ServerContext* /*context*/, const ::ValidationRequest* /*request*/, ::ValidationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedValidateMesh(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ValidationRequest,::ValidationReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamMesh() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MeshRequest, ::MeshReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MeshRequest, ::MeshReply>* streamer) {
                       return this->StreamedStreamMesh(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::MeshReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamMesh(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MeshRequest,::MeshReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ValidateMesh<WithStreamedUnaryMethod_StreamMesh<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ValidateMesh<WithStreamedUnaryMethod_StreamMesh<Service > > StreamedService;
};


#endif  // GRPC_MeshStream_2eproto__INCLUDED
