// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MeshStream.proto
// Protobuf C++ Version: 5.28.3

#include "MeshStream.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ValidationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ValidationRequest::ValidationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ValidationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationRequestDefaultTypeInternal() {}
  union {
    ValidationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationRequestDefaultTypeInternal _ValidationRequest_default_instance_;

inline constexpr ValidationReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : exists_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ValidationReply::ValidationReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ValidationReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidationReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationReplyDefaultTypeInternal() {}
  union {
    ValidationReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationReplyDefaultTypeInternal _ValidationReply_default_instance_;

inline constexpr MeshRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : meshid_{0},
        chunkid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MeshRequest::MeshRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MeshRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshRequestDefaultTypeInternal() {}
  union {
    MeshRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshRequestDefaultTypeInternal _MeshRequest_default_instance_;

inline constexpr Float3::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Float3::Float3(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Float3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Float3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Float3DefaultTypeInternal() {}
  union {
    Float3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Float3DefaultTypeInternal _Float3_default_instance_;

inline constexpr MeshReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chunkvertices_{},
        meshid_{0},
        chunkid_{0},
        numchunks_{0},
        numvertices_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MeshReply::MeshReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MeshReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshReplyDefaultTypeInternal() {}
  union {
    MeshReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshReplyDefaultTypeInternal _MeshReply_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_MeshStream_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MeshStream_2eproto = nullptr;
const ::uint32_t
    TableStruct_MeshStream_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ValidationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ValidationRequest, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ValidationReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ValidationReply, _impl_.exists_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MeshRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MeshRequest, _impl_.meshid_),
        PROTOBUF_FIELD_OFFSET(::MeshRequest, _impl_.chunkid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MeshReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MeshReply, _impl_.meshid_),
        PROTOBUF_FIELD_OFFSET(::MeshReply, _impl_.chunkid_),
        PROTOBUF_FIELD_OFFSET(::MeshReply, _impl_.numchunks_),
        PROTOBUF_FIELD_OFFSET(::MeshReply, _impl_.numvertices_),
        PROTOBUF_FIELD_OFFSET(::MeshReply, _impl_.chunkvertices_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Float3, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.z_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ValidationRequest)},
        {9, -1, -1, sizeof(::ValidationReply)},
        {18, -1, -1, sizeof(::MeshRequest)},
        {28, -1, -1, sizeof(::MeshReply)},
        {41, -1, -1, sizeof(::Float3)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ValidationRequest_default_instance_._instance,
    &::_ValidationReply_default_instance_._instance,
    &::_MeshRequest_default_instance_._instance,
    &::_MeshReply_default_instance_._instance,
    &::_Float3_default_instance_._instance,
};
const char descriptor_table_protodef_MeshStream_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020MeshStream.proto\"\037\n\021ValidationRequest\022"
    "\n\n\002ID\030\001 \001(\005\"!\n\017ValidationReply\022\016\n\006exists"
    "\030\001 \001(\010\".\n\013MeshRequest\022\016\n\006meshID\030\001 \001(\005\022\017\n"
    "\007chunkID\030\002 \001(\005\"t\n\tMeshReply\022\016\n\006meshID\030\001 "
    "\001(\005\022\017\n\007chunkID\030\002 \001(\005\022\021\n\tnumChunks\030\003 \001(\005\022"
    "\023\n\013numVertices\030\004 \001(\005\022\036\n\rchunkVertices\030\005 "
    "\003(\0132\007.Float3\")\n\006Float3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002"
    " \001(\002\022\t\n\001z\030\003 \001(\0022n\n\nMeshStream\0226\n\014Validat"
    "eMesh\022\022.ValidationRequest\032\020.ValidationRe"
    "ply\"\000\022(\n\nStreamMesh\022\014.MeshRequest\032\n.Mesh"
    "Reply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_MeshStream_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MeshStream_2eproto = {
    false,
    false,
    415,
    descriptor_table_protodef_MeshStream_2eproto,
    "MeshStream.proto",
    &descriptor_table_MeshStream_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_MeshStream_2eproto::offsets,
    file_level_enum_descriptors_MeshStream_2eproto,
    file_level_service_descriptors_MeshStream_2eproto,
};
// ===================================================================

class ValidationRequest::_Internal {
 public:
};

ValidationRequest::ValidationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ValidationRequest)
}
ValidationRequest::ValidationRequest(
    ::google::protobuf::Arena* arena, const ValidationRequest& from)
    : ValidationRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ValidationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ValidationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
ValidationRequest::~ValidationRequest() {
  // @@protoc_insertion_point(destructor:ValidationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ValidationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ValidationRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ValidationRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ValidationRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ValidationRequest>(),
            ::google::protobuf::Message::GetNewImpl<ValidationRequest>(),
            ::google::protobuf::Message::GetClearImpl<ValidationRequest>(), &ValidationRequest::ByteSizeLong,
                &ValidationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_._cached_size_),
            false,
        },
        &ValidationRequest::kDescriptorMethods,
        &descriptor_table_MeshStream_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ValidationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ValidationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ValidationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ValidationRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ValidationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ValidationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ValidationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ValidationRequest& this_ = static_cast<const ValidationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ValidationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ValidationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ValidationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 ID = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ValidationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ValidationRequest::ByteSizeLong(const MessageLite& base) {
          const ValidationRequest& this_ = static_cast<const ValidationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ValidationRequest::ByteSizeLong() const {
          const ValidationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ValidationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ValidationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ValidationRequest*>(&to_msg);
  auto& from = static_cast<const ValidationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ValidationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ValidationRequest::CopyFrom(const ValidationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ValidationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidationRequest::InternalSwap(ValidationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata ValidationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ValidationReply::_Internal {
 public:
};

ValidationReply::ValidationReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ValidationReply)
}
ValidationReply::ValidationReply(
    ::google::protobuf::Arena* arena, const ValidationReply& from)
    : ValidationReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ValidationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ValidationReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.exists_ = {};
}
ValidationReply::~ValidationReply() {
  // @@protoc_insertion_point(destructor:ValidationReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ValidationReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ValidationReply::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ValidationReply_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ValidationReply::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ValidationReply>(),
            ::google::protobuf::Message::GetNewImpl<ValidationReply>(),
            ::google::protobuf::Message::GetClearImpl<ValidationReply>(), &ValidationReply::ByteSizeLong,
                &ValidationReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_._cached_size_),
            false,
        },
        &ValidationReply::kDescriptorMethods,
        &descriptor_table_MeshStream_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ValidationReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ValidationReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ValidationReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool exists = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ValidationReply, _impl_.exists_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_.exists_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool exists = 1;
    {PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_.exists_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ValidationReply::Clear() {
// @@protoc_insertion_point(message_clear_start:ValidationReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.exists_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ValidationReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ValidationReply& this_ = static_cast<const ValidationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ValidationReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ValidationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ValidationReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool exists = 1;
          if (this_._internal_exists() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_exists(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ValidationReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ValidationReply::ByteSizeLong(const MessageLite& base) {
          const ValidationReply& this_ = static_cast<const ValidationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ValidationReply::ByteSizeLong() const {
          const ValidationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ValidationReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool exists = 1;
            if (this_._internal_exists() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ValidationReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ValidationReply*>(&to_msg);
  auto& from = static_cast<const ValidationReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ValidationReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_exists() != 0) {
    _this->_impl_.exists_ = from._impl_.exists_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ValidationReply::CopyFrom(const ValidationReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ValidationReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidationReply::InternalSwap(ValidationReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.exists_, other->_impl_.exists_);
}

::google::protobuf::Metadata ValidationReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MeshRequest::_Internal {
 public:
};

MeshRequest::MeshRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MeshRequest)
}
MeshRequest::MeshRequest(
    ::google::protobuf::Arena* arena, const MeshRequest& from)
    : MeshRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MeshRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MeshRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, meshid_),
           0,
           offsetof(Impl_, chunkid_) -
               offsetof(Impl_, meshid_) +
               sizeof(Impl_::chunkid_));
}
MeshRequest::~MeshRequest() {
  // @@protoc_insertion_point(destructor:MeshRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MeshRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MeshRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MeshRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MeshRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MeshRequest>(),
            ::google::protobuf::Message::GetNewImpl<MeshRequest>(),
            ::google::protobuf::Message::GetClearImpl<MeshRequest>(), &MeshRequest::ByteSizeLong,
                &MeshRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_._cached_size_),
            false,
        },
        &MeshRequest::kDescriptorMethods,
        &descriptor_table_MeshStream_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MeshRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MeshRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MeshRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 chunkID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshRequest, _impl_.chunkid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.chunkid_)}},
    // int32 meshID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshRequest, _impl_.meshid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.meshid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 meshID = 1;
    {PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.meshid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 chunkID = 2;
    {PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.chunkid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MeshRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MeshRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.meshid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.chunkid_) -
      reinterpret_cast<char*>(&_impl_.meshid_)) + sizeof(_impl_.chunkid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MeshRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MeshRequest& this_ = static_cast<const MeshRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MeshRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MeshRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MeshRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 meshID = 1;
          if (this_._internal_meshid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_meshid(), target);
          }

          // int32 chunkID = 2;
          if (this_._internal_chunkid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_chunkid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MeshRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MeshRequest::ByteSizeLong(const MessageLite& base) {
          const MeshRequest& this_ = static_cast<const MeshRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MeshRequest::ByteSizeLong() const {
          const MeshRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MeshRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 meshID = 1;
            if (this_._internal_meshid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_meshid());
            }
            // int32 chunkID = 2;
            if (this_._internal_chunkid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chunkid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MeshRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MeshRequest*>(&to_msg);
  auto& from = static_cast<const MeshRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MeshRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_meshid() != 0) {
    _this->_impl_.meshid_ = from._impl_.meshid_;
  }
  if (from._internal_chunkid() != 0) {
    _this->_impl_.chunkid_ = from._impl_.chunkid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MeshRequest::CopyFrom(const MeshRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MeshRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MeshRequest::InternalSwap(MeshRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.chunkid_)
      + sizeof(MeshRequest::_impl_.chunkid_)
      - PROTOBUF_FIELD_OFFSET(MeshRequest, _impl_.meshid_)>(
          reinterpret_cast<char*>(&_impl_.meshid_),
          reinterpret_cast<char*>(&other->_impl_.meshid_));
}

::google::protobuf::Metadata MeshRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MeshReply::_Internal {
 public:
};

MeshReply::MeshReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MeshReply)
}
inline PROTOBUF_NDEBUG_INLINE MeshReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MeshReply& from_msg)
      : chunkvertices_{visibility, arena, from.chunkvertices_},
        _cached_size_{0} {}

MeshReply::MeshReply(
    ::google::protobuf::Arena* arena,
    const MeshReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MeshReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, meshid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, meshid_),
           offsetof(Impl_, numvertices_) -
               offsetof(Impl_, meshid_) +
               sizeof(Impl_::numvertices_));

  // @@protoc_insertion_point(copy_constructor:MeshReply)
}
inline PROTOBUF_NDEBUG_INLINE MeshReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chunkvertices_{visibility, arena},
        _cached_size_{0} {}

inline void MeshReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, meshid_),
           0,
           offsetof(Impl_, numvertices_) -
               offsetof(Impl_, meshid_) +
               sizeof(Impl_::numvertices_));
}
MeshReply::~MeshReply() {
  // @@protoc_insertion_point(destructor:MeshReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MeshReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MeshReply::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MeshReply_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MeshReply::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MeshReply>(),
            ::google::protobuf::Message::GetNewImpl<MeshReply>(),
            ::google::protobuf::Message::GetClearImpl<MeshReply>(), &MeshReply::ByteSizeLong,
                &MeshReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MeshReply, _impl_._cached_size_),
            false,
        },
        &MeshReply::kDescriptorMethods,
        &descriptor_table_MeshStream_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MeshReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 0, 2> MeshReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MeshReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 meshID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshReply, _impl_.meshid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.meshid_)}},
    // int32 chunkID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshReply, _impl_.chunkid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.chunkid_)}},
    // int32 numChunks = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshReply, _impl_.numchunks_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.numchunks_)}},
    // int32 numVertices = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MeshReply, _impl_.numvertices_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.numvertices_)}},
    // repeated .Float3 chunkVertices = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.chunkvertices_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 meshID = 1;
    {PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.meshid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 chunkID = 2;
    {PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.chunkid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 numChunks = 3;
    {PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.numchunks_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 numVertices = 4;
    {PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.numvertices_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .Float3 chunkVertices = 5;
    {PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.chunkvertices_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Float3>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MeshReply::Clear() {
// @@protoc_insertion_point(message_clear_start:MeshReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chunkvertices_.Clear();
  ::memset(&_impl_.meshid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.numvertices_) -
      reinterpret_cast<char*>(&_impl_.meshid_)) + sizeof(_impl_.numvertices_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MeshReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MeshReply& this_ = static_cast<const MeshReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MeshReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MeshReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MeshReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 meshID = 1;
          if (this_._internal_meshid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_meshid(), target);
          }

          // int32 chunkID = 2;
          if (this_._internal_chunkid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_chunkid(), target);
          }

          // int32 numChunks = 3;
          if (this_._internal_numchunks() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_numchunks(), target);
          }

          // int32 numVertices = 4;
          if (this_._internal_numvertices() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_numvertices(), target);
          }

          // repeated .Float3 chunkVertices = 5;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_chunkvertices_size());
               i < n; i++) {
            const auto& repfield = this_._internal_chunkvertices().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    5, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MeshReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MeshReply::ByteSizeLong(const MessageLite& base) {
          const MeshReply& this_ = static_cast<const MeshReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MeshReply::ByteSizeLong() const {
          const MeshReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MeshReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .Float3 chunkVertices = 5;
             {
              total_size += 1UL * this_._internal_chunkvertices_size();
              for (const auto& msg : this_._internal_chunkvertices()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int32 meshID = 1;
            if (this_._internal_meshid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_meshid());
            }
            // int32 chunkID = 2;
            if (this_._internal_chunkid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chunkid());
            }
            // int32 numChunks = 3;
            if (this_._internal_numchunks() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_numchunks());
            }
            // int32 numVertices = 4;
            if (this_._internal_numvertices() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_numvertices());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MeshReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MeshReply*>(&to_msg);
  auto& from = static_cast<const MeshReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MeshReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_chunkvertices()->MergeFrom(
      from._internal_chunkvertices());
  if (from._internal_meshid() != 0) {
    _this->_impl_.meshid_ = from._impl_.meshid_;
  }
  if (from._internal_chunkid() != 0) {
    _this->_impl_.chunkid_ = from._impl_.chunkid_;
  }
  if (from._internal_numchunks() != 0) {
    _this->_impl_.numchunks_ = from._impl_.numchunks_;
  }
  if (from._internal_numvertices() != 0) {
    _this->_impl_.numvertices_ = from._impl_.numvertices_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MeshReply::CopyFrom(const MeshReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MeshReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MeshReply::InternalSwap(MeshReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.chunkvertices_.InternalSwap(&other->_impl_.chunkvertices_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.numvertices_)
      + sizeof(MeshReply::_impl_.numvertices_)
      - PROTOBUF_FIELD_OFFSET(MeshReply, _impl_.meshid_)>(
          reinterpret_cast<char*>(&_impl_.meshid_),
          reinterpret_cast<char*>(&other->_impl_.meshid_));
}

::google::protobuf::Metadata MeshReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Float3::_Internal {
 public:
};

Float3::Float3(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Float3)
}
Float3::Float3(
    ::google::protobuf::Arena* arena, const Float3& from)
    : Float3(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Float3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Float3::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Float3::~Float3() {
  // @@protoc_insertion_point(destructor:Float3)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Float3::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Float3::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Float3_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Float3::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Float3>(),
            ::google::protobuf::Message::GetNewImpl<Float3>(),
            ::google::protobuf::Message::GetClearImpl<Float3>(), &Float3::ByteSizeLong,
                &Float3::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Float3, _impl_._cached_size_),
            false,
        },
        &Float3::kDescriptorMethods,
        &descriptor_table_MeshStream_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Float3::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Float3::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Float3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Float3::Clear() {
// @@protoc_insertion_point(message_clear_start:Float3)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Float3::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Float3& this_ = static_cast<const Float3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Float3::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Float3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Float3)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x(), target);
          }

          // float y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y(), target);
          }

          // float z = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Float3)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Float3::ByteSizeLong(const MessageLite& base) {
          const Float3& this_ = static_cast<const Float3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Float3::ByteSizeLong() const {
          const Float3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Float3)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
              total_size += 5;
            }
            // float y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
              total_size += 5;
            }
            // float z = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Float3::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Float3*>(&to_msg);
  auto& from = static_cast<const Float3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Float3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Float3::CopyFrom(const Float3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Float3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Float3::InternalSwap(Float3* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_)
      + sizeof(Float3::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Float3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_MeshStream_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
