// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SceneData.proto

#include "SceneData.pb.h"
#include "SceneData.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* MeshStream_method_names[] = {
  "/MeshStream/StreamMesh",
};

std::unique_ptr< MeshStream::Stub> MeshStream::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MeshStream::Stub> stub(new MeshStream::Stub(channel, options));
  return stub;
}

MeshStream::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamMesh_(MeshStream_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::MeshReply>* MeshStream::Stub::StreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::MeshReply>::Create(channel_.get(), rpcmethod_StreamMesh_, context, request);
}

void MeshStream::Stub::async::StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::grpc::ClientReadReactor< ::MeshReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::MeshReply>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamMesh_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::MeshReply>* MeshStream::Stub::AsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::MeshReply>::Create(channel_.get(), cq, rpcmethod_StreamMesh_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::MeshReply>* MeshStream::Stub::PrepareAsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::MeshReply>::Create(channel_.get(), cq, rpcmethod_StreamMesh_, context, request, false, nullptr);
}

MeshStream::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeshStream_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MeshStream::Service, ::MeshRequest, ::MeshReply>(
          [](MeshStream::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MeshRequest* req,
             ::grpc::ServerWriter<::MeshReply>* writer) {
               return service->StreamMesh(ctx, req, writer);
             }, this)));
}

MeshStream::Service::~Service() {
}

::grpc::Status MeshStream::Service::StreamMesh(::grpc::ServerContext* context, const ::MeshRequest* request, ::grpc::ServerWriter< ::MeshReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* SceneLoad_method_names[] = {
  "/SceneLoad/LoadScene",
};

std::unique_ptr< SceneLoad::Stub> SceneLoad::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneLoad::Stub> stub(new SceneLoad::Stub(channel, options));
  return stub;
}

SceneLoad::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_LoadScene_(SceneLoad_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SceneLoad::Stub::LoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::SceneReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SceneRequest, ::SceneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadScene_, context, request, response);
}

void SceneLoad::Stub::async::LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SceneRequest, ::SceneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadScene_, context, request, response, std::move(f));
}

void SceneLoad::Stub::async::LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadScene_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SceneReply>* SceneLoad::Stub::PrepareAsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SceneReply, ::SceneRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadScene_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SceneReply>* SceneLoad::Stub::AsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadSceneRaw(context, request, cq);
  result->StartCall();
  return result;
}

SceneLoad::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneLoad_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SceneLoad::Service, ::SceneRequest, ::SceneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SceneLoad::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneRequest* req,
             ::SceneReply* resp) {
               return service->LoadScene(ctx, req, resp);
             }, this)));
}

SceneLoad::Service::~Service() {
}

::grpc::Status SceneLoad::Service::LoadScene(::grpc::ServerContext* context, const ::SceneRequest* request, ::SceneReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


