// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SceneData.proto
// Protobuf C++ Version: 5.29.1

#ifndef SceneData_2eproto_2epb_2eh
#define SceneData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SceneData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SceneData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SceneData_2eproto;
class Float3;
struct Float3DefaultTypeInternal;
extern Float3DefaultTypeInternal _Float3_default_instance_;
class MeshReply;
struct MeshReplyDefaultTypeInternal;
extern MeshReplyDefaultTypeInternal _MeshReply_default_instance_;
class MeshRequest;
struct MeshRequestDefaultTypeInternal;
extern MeshRequestDefaultTypeInternal _MeshRequest_default_instance_;
class SceneReply;
struct SceneReplyDefaultTypeInternal;
extern SceneReplyDefaultTypeInternal _SceneReply_default_instance_;
class SceneRequest;
struct SceneRequestDefaultTypeInternal;
extern SceneRequestDefaultTypeInternal _SceneRequest_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SceneRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SceneRequest) */ {
 public:
  inline SceneRequest() : SceneRequest(nullptr) {}
  ~SceneRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SceneRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SceneRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SceneRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline SceneRequest(const SceneRequest& from) : SceneRequest(nullptr, from) {}
  inline SceneRequest(SceneRequest&& from) noexcept
      : SceneRequest(nullptr, std::move(from)) {}
  inline SceneRequest& operator=(const SceneRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneRequest& operator=(SceneRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneRequest* internal_default_instance() {
    return reinterpret_cast<const SceneRequest*>(
        &_SceneRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SceneRequest& a, SceneRequest& b) { a.Swap(&b); }
  inline void Swap(SceneRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SceneRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SceneRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SceneRequest& from) { SceneRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SceneRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SceneRequest"; }

 protected:
  explicit SceneRequest(::google::protobuf::Arena* arena);
  SceneRequest(::google::protobuf::Arena* arena, const SceneRequest& from);
  SceneRequest(::google::protobuf::Arena* arena, SceneRequest&& from) noexcept
      : SceneRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSceneIDFieldNumber = 1,
  };
  // string sceneID = 1;
  void clear_sceneid() ;
  const std::string& sceneid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sceneid(Arg_&& arg, Args_... args);
  std::string* mutable_sceneid();
  PROTOBUF_NODISCARD std::string* release_sceneid();
  void set_allocated_sceneid(std::string* value);

  private:
  const std::string& _internal_sceneid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sceneid(
      const std::string& value);
  std::string* _internal_mutable_sceneid();

  public:
  // @@protoc_insertion_point(class_scope:SceneRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      28, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SceneRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr sceneid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SceneData_2eproto;
};
// -------------------------------------------------------------------

class MeshRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MeshRequest) */ {
 public:
  inline MeshRequest() : MeshRequest(nullptr) {}
  ~MeshRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MeshRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MeshRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MeshRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline MeshRequest(const MeshRequest& from) : MeshRequest(nullptr, from) {}
  inline MeshRequest(MeshRequest&& from) noexcept
      : MeshRequest(nullptr, std::move(from)) {}
  inline MeshRequest& operator=(const MeshRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshRequest& operator=(MeshRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshRequest* internal_default_instance() {
    return reinterpret_cast<const MeshRequest*>(
        &_MeshRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MeshRequest& a, MeshRequest& b) { a.Swap(&b); }
  inline void Swap(MeshRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MeshRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MeshRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MeshRequest& from) { MeshRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MeshRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MeshRequest"; }

 protected:
  explicit MeshRequest(::google::protobuf::Arena* arena);
  MeshRequest(::google::protobuf::Arena* arena, const MeshRequest& from);
  MeshRequest(::google::protobuf::Arena* arena, MeshRequest&& from) noexcept
      : MeshRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFileNameFieldNumber = 1,
  };
  // string file_name = 1;
  void clear_file_name() ;
  const std::string& file_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file_name(Arg_&& arg, Args_... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* value);

  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(
      const std::string& value);
  std::string* _internal_mutable_file_name();

  public:
  // @@protoc_insertion_point(class_scope:MeshRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      29, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MeshRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr file_name_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SceneData_2eproto;
};
// -------------------------------------------------------------------

class MeshReply final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MeshReply) */ {
 public:
  inline MeshReply() : MeshReply(nullptr) {}
  ~MeshReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MeshReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MeshReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MeshReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline MeshReply(const MeshReply& from) : MeshReply(nullptr, from) {}
  inline MeshReply(MeshReply&& from) noexcept
      : MeshReply(nullptr, std::move(from)) {}
  inline MeshReply& operator=(const MeshReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshReply& operator=(MeshReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshReply* internal_default_instance() {
    return reinterpret_cast<const MeshReply*>(
        &_MeshReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MeshReply& a, MeshReply& b) { a.Swap(&b); }
  inline void Swap(MeshReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MeshReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MeshReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MeshReply& from) { MeshReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MeshReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MeshReply"; }

 protected:
  explicit MeshReply(::google::protobuf::Arena* arena);
  MeshReply(::google::protobuf::Arena* arena, const MeshReply& from);
  MeshReply(::google::protobuf::Arena* arena, MeshReply&& from) noexcept
      : MeshReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:MeshReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MeshReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SceneData_2eproto;
};
// -------------------------------------------------------------------

class Float3 final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Float3) */ {
 public:
  inline Float3() : Float3(nullptr) {}
  ~Float3() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Float3* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Float3));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Float3(
      ::google::protobuf::internal::ConstantInitialized);

  inline Float3(const Float3& from) : Float3(nullptr, from) {}
  inline Float3(Float3&& from) noexcept
      : Float3(nullptr, std::move(from)) {}
  inline Float3& operator=(const Float3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Float3& operator=(Float3&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Float3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Float3* internal_default_instance() {
    return reinterpret_cast<const Float3*>(
        &_Float3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Float3& a, Float3& b) { a.Swap(&b); }
  inline void Swap(Float3* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Float3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Float3* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Float3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Float3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Float3& from) { Float3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Float3* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Float3"; }

 protected:
  explicit Float3(::google::protobuf::Arena* arena);
  Float3(::google::protobuf::Arena* arena, const Float3& from);
  Float3(::google::protobuf::Arena* arena, Float3&& from) noexcept
      : Float3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Float3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Float3& from_msg);
    float x_;
    float y_;
    float z_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SceneData_2eproto;
};
// -------------------------------------------------------------------

class SceneReply final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SceneReply) */ {
 public:
  inline SceneReply() : SceneReply(nullptr) {}
  ~SceneReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SceneReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SceneReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SceneReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline SceneReply(const SceneReply& from) : SceneReply(nullptr, from) {}
  inline SceneReply(SceneReply&& from) noexcept
      : SceneReply(nullptr, std::move(from)) {}
  inline SceneReply& operator=(const SceneReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneReply& operator=(SceneReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneReply* internal_default_instance() {
    return reinterpret_cast<const SceneReply*>(
        &_SceneReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(SceneReply& a, SceneReply& b) { a.Swap(&b); }
  inline void Swap(SceneReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SceneReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SceneReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SceneReply& from) { SceneReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SceneReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SceneReply"; }

 protected:
  explicit SceneReply(::google::protobuf::Arena* arena);
  SceneReply(::google::protobuf::Arena* arena, const SceneReply& from);
  SceneReply(::google::protobuf::Arena* arena, SceneReply&& from) noexcept
      : SceneReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMeshIDsFieldNumber = 2,
    kPositionsFieldNumber = 3,
    kScalesFieldNumber = 4,
    kSceneIDFieldNumber = 1,
  };
  // repeated string meshIDs = 2;
  int meshids_size() const;
  private:
  int _internal_meshids_size() const;

  public:
  void clear_meshids() ;
  const std::string& meshids(int index) const;
  std::string* mutable_meshids(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_meshids(int index, Arg_&& value, Args_... args);
  std::string* add_meshids();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_meshids(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& meshids() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_meshids();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_meshids() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_meshids();

  public:
  // repeated .Float3 positions = 3;
  int positions_size() const;
  private:
  int _internal_positions_size() const;

  public:
  void clear_positions() ;
  ::Float3* mutable_positions(int index);
  ::google::protobuf::RepeatedPtrField<::Float3>* mutable_positions();

  private:
  const ::google::protobuf::RepeatedPtrField<::Float3>& _internal_positions() const;
  ::google::protobuf::RepeatedPtrField<::Float3>* _internal_mutable_positions();
  public:
  const ::Float3& positions(int index) const;
  ::Float3* add_positions();
  const ::google::protobuf::RepeatedPtrField<::Float3>& positions() const;
  // repeated .Float3 scales = 4;
  int scales_size() const;
  private:
  int _internal_scales_size() const;

  public:
  void clear_scales() ;
  ::Float3* mutable_scales(int index);
  ::google::protobuf::RepeatedPtrField<::Float3>* mutable_scales();

  private:
  const ::google::protobuf::RepeatedPtrField<::Float3>& _internal_scales() const;
  ::google::protobuf::RepeatedPtrField<::Float3>* _internal_mutable_scales();
  public:
  const ::Float3& scales(int index) const;
  ::Float3* add_scales();
  const ::google::protobuf::RepeatedPtrField<::Float3>& scales() const;
  // string sceneID = 1;
  void clear_sceneid() ;
  const std::string& sceneid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sceneid(Arg_&& arg, Args_... args);
  std::string* mutable_sceneid();
  PROTOBUF_NODISCARD std::string* release_sceneid();
  void set_allocated_sceneid(std::string* value);

  private:
  const std::string& _internal_sceneid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sceneid(
      const std::string& value);
  std::string* _internal_mutable_sceneid();

  public:
  // @@protoc_insertion_point(class_scope:SceneReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 2,
      33, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SceneReply& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> meshids_;
    ::google::protobuf::RepeatedPtrField< ::Float3 > positions_;
    ::google::protobuf::RepeatedPtrField< ::Float3 > scales_;
    ::google::protobuf::internal::ArenaStringPtr sceneid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SceneData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Float3

// float x = 1;
inline void Float3::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float Float3::x() const {
  // @@protoc_insertion_point(field_get:Float3.x)
  return _internal_x();
}
inline void Float3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Float3.x)
}
inline float Float3::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Float3::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Float3::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float Float3::y() const {
  // @@protoc_insertion_point(field_get:Float3.y)
  return _internal_y();
}
inline void Float3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Float3.y)
}
inline float Float3::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Float3::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Float3::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline float Float3::z() const {
  // @@protoc_insertion_point(field_get:Float3.z)
  return _internal_z();
}
inline void Float3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Float3.z)
}
inline float Float3::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Float3::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// MeshRequest

// string file_name = 1;
inline void MeshRequest::clear_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.ClearToEmpty();
}
inline const std::string& MeshRequest::file_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MeshRequest.file_name)
  return _internal_file_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MeshRequest::set_file_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MeshRequest.file_name)
}
inline std::string* MeshRequest::mutable_file_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:MeshRequest.file_name)
  return _s;
}
inline const std::string& MeshRequest::_internal_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_name_.Get();
}
inline void MeshRequest::_internal_set_file_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.Set(value, GetArena());
}
inline std::string* MeshRequest::_internal_mutable_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.file_name_.Mutable( GetArena());
}
inline std::string* MeshRequest::release_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MeshRequest.file_name)
  return _impl_.file_name_.Release();
}
inline void MeshRequest::set_allocated_file_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.file_name_.IsDefault()) {
    _impl_.file_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MeshRequest.file_name)
}

// -------------------------------------------------------------------

// MeshReply

// bytes data = 1;
inline void MeshReply::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& MeshReply::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MeshReply.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MeshReply::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MeshReply.data)
}
inline std::string* MeshReply::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:MeshReply.data)
  return _s;
}
inline const std::string& MeshReply::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void MeshReply::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* MeshReply::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* MeshReply::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MeshReply.data)
  return _impl_.data_.Release();
}
inline void MeshReply::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MeshReply.data)
}

// -------------------------------------------------------------------

// SceneRequest

// string sceneID = 1;
inline void SceneRequest::clear_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.ClearToEmpty();
}
inline const std::string& SceneRequest::sceneid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SceneRequest.sceneID)
  return _internal_sceneid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SceneRequest::set_sceneid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:SceneRequest.sceneID)
}
inline std::string* SceneRequest::mutable_sceneid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sceneid();
  // @@protoc_insertion_point(field_mutable:SceneRequest.sceneID)
  return _s;
}
inline const std::string& SceneRequest::_internal_sceneid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sceneid_.Get();
}
inline void SceneRequest::_internal_set_sceneid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.Set(value, GetArena());
}
inline std::string* SceneRequest::_internal_mutable_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sceneid_.Mutable( GetArena());
}
inline std::string* SceneRequest::release_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SceneRequest.sceneID)
  return _impl_.sceneid_.Release();
}
inline void SceneRequest::set_allocated_sceneid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sceneid_.IsDefault()) {
    _impl_.sceneid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:SceneRequest.sceneID)
}

// -------------------------------------------------------------------

// SceneReply

// string sceneID = 1;
inline void SceneReply::clear_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.ClearToEmpty();
}
inline const std::string& SceneReply::sceneid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SceneReply.sceneID)
  return _internal_sceneid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SceneReply::set_sceneid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:SceneReply.sceneID)
}
inline std::string* SceneReply::mutable_sceneid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sceneid();
  // @@protoc_insertion_point(field_mutable:SceneReply.sceneID)
  return _s;
}
inline const std::string& SceneReply::_internal_sceneid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sceneid_.Get();
}
inline void SceneReply::_internal_set_sceneid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.Set(value, GetArena());
}
inline std::string* SceneReply::_internal_mutable_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sceneid_.Mutable( GetArena());
}
inline std::string* SceneReply::release_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SceneReply.sceneID)
  return _impl_.sceneid_.Release();
}
inline void SceneReply::set_allocated_sceneid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sceneid_.IsDefault()) {
    _impl_.sceneid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:SceneReply.sceneID)
}

// repeated string meshIDs = 2;
inline int SceneReply::_internal_meshids_size() const {
  return _internal_meshids().size();
}
inline int SceneReply::meshids_size() const {
  return _internal_meshids_size();
}
inline void SceneReply::clear_meshids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.meshids_.Clear();
}
inline std::string* SceneReply::add_meshids() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_meshids()->Add();
  // @@protoc_insertion_point(field_add_mutable:SceneReply.meshIDs)
  return _s;
}
inline const std::string& SceneReply::meshids(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SceneReply.meshIDs)
  return _internal_meshids().Get(index);
}
inline std::string* SceneReply::mutable_meshids(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:SceneReply.meshIDs)
  return _internal_mutable_meshids()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SceneReply::set_meshids(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_meshids()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:SceneReply.meshIDs)
}
template <typename Arg_, typename... Args_>
inline void SceneReply::add_meshids(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_meshids(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:SceneReply.meshIDs)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SceneReply::meshids() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:SceneReply.meshIDs)
  return _internal_meshids();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SceneReply::mutable_meshids() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:SceneReply.meshIDs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_meshids();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SceneReply::_internal_meshids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.meshids_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SceneReply::_internal_mutable_meshids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.meshids_;
}

// repeated .Float3 positions = 3;
inline int SceneReply::_internal_positions_size() const {
  return _internal_positions().size();
}
inline int SceneReply::positions_size() const {
  return _internal_positions_size();
}
inline void SceneReply::clear_positions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.positions_.Clear();
}
inline ::Float3* SceneReply::mutable_positions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:SceneReply.positions)
  return _internal_mutable_positions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Float3>* SceneReply::mutable_positions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:SceneReply.positions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_positions();
}
inline const ::Float3& SceneReply::positions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SceneReply.positions)
  return _internal_positions().Get(index);
}
inline ::Float3* SceneReply::add_positions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Float3* _add = _internal_mutable_positions()->Add();
  // @@protoc_insertion_point(field_add:SceneReply.positions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Float3>& SceneReply::positions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:SceneReply.positions)
  return _internal_positions();
}
inline const ::google::protobuf::RepeatedPtrField<::Float3>&
SceneReply::_internal_positions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.positions_;
}
inline ::google::protobuf::RepeatedPtrField<::Float3>*
SceneReply::_internal_mutable_positions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.positions_;
}

// repeated .Float3 scales = 4;
inline int SceneReply::_internal_scales_size() const {
  return _internal_scales().size();
}
inline int SceneReply::scales_size() const {
  return _internal_scales_size();
}
inline void SceneReply::clear_scales() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scales_.Clear();
}
inline ::Float3* SceneReply::mutable_scales(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:SceneReply.scales)
  return _internal_mutable_scales()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Float3>* SceneReply::mutable_scales()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:SceneReply.scales)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_scales();
}
inline const ::Float3& SceneReply::scales(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SceneReply.scales)
  return _internal_scales().Get(index);
}
inline ::Float3* SceneReply::add_scales() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Float3* _add = _internal_mutable_scales()->Add();
  // @@protoc_insertion_point(field_add:SceneReply.scales)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Float3>& SceneReply::scales() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:SceneReply.scales)
  return _internal_scales();
}
inline const ::google::protobuf::RepeatedPtrField<::Float3>&
SceneReply::_internal_scales() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scales_;
}
inline ::google::protobuf::RepeatedPtrField<::Float3>*
SceneReply::_internal_mutable_scales() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.scales_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SceneData_2eproto_2epb_2eh
