// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SceneData.proto
#ifndef GRPC_SceneData_2eproto__INCLUDED
#define GRPC_SceneData_2eproto__INCLUDED

#include "SceneData.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class MeshStream final {
 public:
  static constexpr char const* service_full_name() {
    return "MeshStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Loads an item
    std::unique_ptr< ::grpc::ClientReaderInterface< ::MeshReply>> StreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::MeshReply>>(StreamMeshRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MeshReply>> AsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MeshReply>>(AsyncStreamMeshRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MeshReply>> PrepareAsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MeshReply>>(PrepareAsyncStreamMeshRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Loads an item
      virtual void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::grpc::ClientReadReactor< ::MeshReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::MeshReply>* StreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::MeshReply>* AsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::MeshReply>* PrepareAsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::MeshReply>> StreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::MeshReply>>(StreamMeshRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::MeshReply>> AsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::MeshReply>>(AsyncStreamMeshRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::MeshReply>> PrepareAsyncStreamMesh(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::MeshReply>>(PrepareAsyncStreamMeshRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamMesh(::grpc::ClientContext* context, const ::MeshRequest* request, ::grpc::ClientReadReactor< ::MeshReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::MeshReply>* StreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request) override;
    ::grpc::ClientAsyncReader< ::MeshReply>* AsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::MeshReply>* PrepareAsyncStreamMeshRaw(::grpc::ClientContext* context, const ::MeshRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamMesh_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Loads an item
    virtual ::grpc::Status StreamMesh(::grpc::ServerContext* context, const ::MeshRequest* request, ::grpc::ServerWriter< ::MeshReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamMesh() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMesh(::grpc::ServerContext* context, ::MeshRequest* request, ::grpc::ServerAsyncWriter< ::MeshReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamMesh<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamMesh() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::MeshRequest, ::MeshReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::MeshRequest* request) { return this->StreamMesh(context, request); }));
    }
    ~WithCallbackMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::MeshReply>* StreamMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::MeshRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamMesh<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamMesh() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamMesh() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMesh(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamMesh() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamMesh(context, request); }));
    }
    ~WithRawCallbackMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamMesh() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::MeshRequest, ::MeshReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::MeshRequest, ::MeshReply>* streamer) {
                       return this->StreamedStreamMesh(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamMesh(::grpc::ServerContext* /*context*/, const ::MeshRequest* /*request*/, ::grpc::ServerWriter< ::MeshReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamMesh(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::MeshRequest,::MeshReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamMesh<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamMesh<Service > StreamedService;
};

class SceneLoad final {
 public:
  static constexpr char const* service_full_name() {
    return "SceneLoad";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Loads a scene
    virtual ::grpc::Status LoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::SceneReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>> AsyncLoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>>(AsyncLoadSceneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>> PrepareAsyncLoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>>(PrepareAsyncLoadSceneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Loads a scene
      virtual void LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>* AsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SceneReply>* PrepareAsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status LoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::SceneReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SceneReply>> AsyncLoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SceneReply>>(AsyncLoadSceneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SceneReply>> PrepareAsyncLoadScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SceneReply>>(PrepareAsyncLoadSceneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, std::function<void(::grpc::Status)>) override;
      void LoadScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SceneReply>* AsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SceneReply>* PrepareAsyncLoadSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_LoadScene_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Loads a scene
    virtual ::grpc::Status LoadScene(::grpc::ServerContext* context, const ::SceneRequest* request, ::SceneReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LoadScene() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadScene(::grpc::ServerContext* context, ::SceneRequest* request, ::grpc::ServerAsyncResponseWriter< ::SceneReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_LoadScene<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LoadScene() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SceneRequest, ::SceneReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SceneRequest* request, ::SceneReply* response) { return this->LoadScene(context, request, response); }));}
    void SetMessageAllocatorFor_LoadScene(
        ::grpc::MessageAllocator< ::SceneRequest, ::SceneReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SceneRequest, ::SceneReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadScene(
      ::grpc::CallbackServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_LoadScene<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LoadScene() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LoadScene() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadScene(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LoadScene() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LoadScene(context, request, response); }));
    }
    ~WithRawCallbackMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadScene(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LoadScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LoadScene() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SceneRequest, ::SceneReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SceneRequest, ::SceneReply>* streamer) {
                       return this->StreamedLoadScene(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LoadScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LoadScene(::grpc::ServerContext* /*context*/, const ::SceneRequest* /*request*/, ::SceneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLoadScene(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SceneRequest,::SceneReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_LoadScene<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_LoadScene<Service > StreamedService;
};


#endif  // GRPC_SceneData_2eproto__INCLUDED
