// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SceneLoad.proto
// Protobuf C++ Version: 5.28.3

#include "SceneLoad.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ValidationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ValidationRequest::ValidationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ValidationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationRequestDefaultTypeInternal() {}
  union {
    ValidationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationRequestDefaultTypeInternal _ValidationRequest_default_instance_;

inline constexpr ValidationReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : exists_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ValidationReply::ValidationReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ValidationReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidationReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationReplyDefaultTypeInternal() {}
  union {
    ValidationReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationReplyDefaultTypeInternal _ValidationReply_default_instance_;

inline constexpr SceneRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sceneid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SceneRequest::SceneRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneRequestDefaultTypeInternal() {}
  union {
    SceneRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneRequestDefaultTypeInternal _SceneRequest_default_instance_;

inline constexpr Float3::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Float3::Float3(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Float3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Float3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Float3DefaultTypeInternal() {}
  union {
    Float3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Float3DefaultTypeInternal _Float3_default_instance_;

inline constexpr SceneReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : meshids_{},
        _meshids_cached_byte_size_{0},
        positions_{},
        sceneid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SceneReply::SceneReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneReplyDefaultTypeInternal() {}
  union {
    SceneReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneReplyDefaultTypeInternal _SceneReply_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SceneLoad_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SceneLoad_2eproto = nullptr;
const ::uint32_t
    TableStruct_SceneLoad_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ValidationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ValidationRequest, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ValidationReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ValidationReply, _impl_.exists_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SceneRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SceneRequest, _impl_.sceneid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SceneReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SceneReply, _impl_.sceneid_),
        PROTOBUF_FIELD_OFFSET(::SceneReply, _impl_.meshids_),
        PROTOBUF_FIELD_OFFSET(::SceneReply, _impl_.positions_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Float3, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::Float3, _impl_.z_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ValidationRequest)},
        {9, -1, -1, sizeof(::ValidationReply)},
        {18, -1, -1, sizeof(::SceneRequest)},
        {27, -1, -1, sizeof(::SceneReply)},
        {38, -1, -1, sizeof(::Float3)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ValidationRequest_default_instance_._instance,
    &::_ValidationReply_default_instance_._instance,
    &::_SceneRequest_default_instance_._instance,
    &::_SceneReply_default_instance_._instance,
    &::_Float3_default_instance_._instance,
};
const char descriptor_table_protodef_SceneLoad_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017SceneLoad.proto\"\037\n\021ValidationRequest\022\n"
    "\n\002ID\030\001 \001(\005\"!\n\017ValidationReply\022\016\n\006exists\030"
    "\001 \001(\010\"\037\n\014SceneRequest\022\017\n\007sceneID\030\001 \001(\005\"J"
    "\n\nSceneReply\022\017\n\007sceneID\030\001 \001(\005\022\017\n\007meshIDs"
    "\030\002 \003(\005\022\032\n\tpositions\030\003 \003(\0132\007.Float3\")\n\006Fl"
    "oat3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\0022o\n"
    "\tSceneLoad\0227\n\rValidateScene\022\022.Validation"
    "Request\032\020.ValidationReply\"\000\022)\n\tLoadScene"
    "\022\r.SceneRequest\032\013.SceneReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_SceneLoad_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SceneLoad_2eproto = {
    false,
    false,
    358,
    descriptor_table_protodef_SceneLoad_2eproto,
    "SceneLoad.proto",
    &descriptor_table_SceneLoad_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_SceneLoad_2eproto::offsets,
    file_level_enum_descriptors_SceneLoad_2eproto,
    file_level_service_descriptors_SceneLoad_2eproto,
};
// ===================================================================

class ValidationRequest::_Internal {
 public:
};

ValidationRequest::ValidationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ValidationRequest)
}
ValidationRequest::ValidationRequest(
    ::google::protobuf::Arena* arena, const ValidationRequest& from)
    : ValidationRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ValidationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ValidationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
ValidationRequest::~ValidationRequest() {
  // @@protoc_insertion_point(destructor:ValidationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ValidationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ValidationRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ValidationRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ValidationRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ValidationRequest>(),
            ::google::protobuf::Message::GetNewImpl<ValidationRequest>(),
            ::google::protobuf::Message::GetClearImpl<ValidationRequest>(), &ValidationRequest::ByteSizeLong,
                &ValidationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_._cached_size_),
            false,
        },
        &ValidationRequest::kDescriptorMethods,
        &descriptor_table_SceneLoad_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ValidationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ValidationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ValidationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ValidationRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(ValidationRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ValidationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ValidationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ValidationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ValidationRequest& this_ = static_cast<const ValidationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ValidationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ValidationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ValidationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 ID = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ValidationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ValidationRequest::ByteSizeLong(const MessageLite& base) {
          const ValidationRequest& this_ = static_cast<const ValidationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ValidationRequest::ByteSizeLong() const {
          const ValidationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ValidationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ValidationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ValidationRequest*>(&to_msg);
  auto& from = static_cast<const ValidationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ValidationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ValidationRequest::CopyFrom(const ValidationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ValidationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidationRequest::InternalSwap(ValidationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata ValidationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ValidationReply::_Internal {
 public:
};

ValidationReply::ValidationReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ValidationReply)
}
ValidationReply::ValidationReply(
    ::google::protobuf::Arena* arena, const ValidationReply& from)
    : ValidationReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ValidationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ValidationReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.exists_ = {};
}
ValidationReply::~ValidationReply() {
  // @@protoc_insertion_point(destructor:ValidationReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ValidationReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ValidationReply::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ValidationReply_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ValidationReply::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ValidationReply>(),
            ::google::protobuf::Message::GetNewImpl<ValidationReply>(),
            ::google::protobuf::Message::GetClearImpl<ValidationReply>(), &ValidationReply::ByteSizeLong,
                &ValidationReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_._cached_size_),
            false,
        },
        &ValidationReply::kDescriptorMethods,
        &descriptor_table_SceneLoad_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ValidationReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ValidationReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ValidationReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool exists = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ValidationReply, _impl_.exists_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_.exists_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool exists = 1;
    {PROTOBUF_FIELD_OFFSET(ValidationReply, _impl_.exists_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ValidationReply::Clear() {
// @@protoc_insertion_point(message_clear_start:ValidationReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.exists_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ValidationReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ValidationReply& this_ = static_cast<const ValidationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ValidationReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ValidationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ValidationReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool exists = 1;
          if (this_._internal_exists() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_exists(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ValidationReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ValidationReply::ByteSizeLong(const MessageLite& base) {
          const ValidationReply& this_ = static_cast<const ValidationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ValidationReply::ByteSizeLong() const {
          const ValidationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ValidationReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool exists = 1;
            if (this_._internal_exists() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ValidationReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ValidationReply*>(&to_msg);
  auto& from = static_cast<const ValidationReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ValidationReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_exists() != 0) {
    _this->_impl_.exists_ = from._impl_.exists_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ValidationReply::CopyFrom(const ValidationReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ValidationReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidationReply::InternalSwap(ValidationReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.exists_, other->_impl_.exists_);
}

::google::protobuf::Metadata ValidationReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SceneRequest::_Internal {
 public:
};

SceneRequest::SceneRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SceneRequest)
}
SceneRequest::SceneRequest(
    ::google::protobuf::Arena* arena, const SceneRequest& from)
    : SceneRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SceneRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SceneRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sceneid_ = {};
}
SceneRequest::~SceneRequest() {
  // @@protoc_insertion_point(destructor:SceneRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SceneRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    SceneRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_SceneRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &SceneRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<SceneRequest>(),
            ::google::protobuf::Message::GetNewImpl<SceneRequest>(),
            ::google::protobuf::Message::GetClearImpl<SceneRequest>(), &SceneRequest::ByteSizeLong,
                &SceneRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_._cached_size_),
            false,
        },
        &SceneRequest::kDescriptorMethods,
        &descriptor_table_SceneLoad_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* SceneRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SceneRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SceneRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 sceneID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SceneRequest, _impl_.sceneid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_.sceneid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sceneID = 1;
    {PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_.sceneid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SceneRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:SceneRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sceneid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SceneRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SceneRequest& this_ = static_cast<const SceneRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SceneRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SceneRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SceneRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 sceneID = 1;
          if (this_._internal_sceneid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_sceneid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SceneRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SceneRequest::ByteSizeLong(const MessageLite& base) {
          const SceneRequest& this_ = static_cast<const SceneRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SceneRequest::ByteSizeLong() const {
          const SceneRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SceneRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 sceneID = 1;
            if (this_._internal_sceneid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sceneid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SceneRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SceneRequest*>(&to_msg);
  auto& from = static_cast<const SceneRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SceneRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sceneid() != 0) {
    _this->_impl_.sceneid_ = from._impl_.sceneid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SceneRequest::CopyFrom(const SceneRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SceneRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SceneRequest::InternalSwap(SceneRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sceneid_, other->_impl_.sceneid_);
}

::google::protobuf::Metadata SceneRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SceneReply::_Internal {
 public:
};

SceneReply::SceneReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SceneReply)
}
inline PROTOBUF_NDEBUG_INLINE SceneReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::SceneReply& from_msg)
      : meshids_{visibility, arena, from.meshids_},
        _meshids_cached_byte_size_{0},
        positions_{visibility, arena, from.positions_},
        _cached_size_{0} {}

SceneReply::SceneReply(
    ::google::protobuf::Arena* arena,
    const SceneReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SceneReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sceneid_ = from._impl_.sceneid_;

  // @@protoc_insertion_point(copy_constructor:SceneReply)
}
inline PROTOBUF_NDEBUG_INLINE SceneReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : meshids_{visibility, arena},
        _meshids_cached_byte_size_{0},
        positions_{visibility, arena},
        _cached_size_{0} {}

inline void SceneReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sceneid_ = {};
}
SceneReply::~SceneReply() {
  // @@protoc_insertion_point(destructor:SceneReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SceneReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    SceneReply::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_SceneReply_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &SceneReply::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<SceneReply>(),
            ::google::protobuf::Message::GetNewImpl<SceneReply>(),
            ::google::protobuf::Message::GetClearImpl<SceneReply>(), &SceneReply::ByteSizeLong,
                &SceneReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(SceneReply, _impl_._cached_size_),
            false,
        },
        &SceneReply::kDescriptorMethods,
        &descriptor_table_SceneLoad_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* SceneReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> SceneReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SceneReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 sceneID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SceneReply, _impl_.sceneid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.sceneid_)}},
    // repeated int32 meshIDs = 2;
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.meshids_)}},
    // repeated .Float3 positions = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.positions_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sceneID = 1;
    {PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.sceneid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated int32 meshIDs = 2;
    {PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.meshids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated .Float3 positions = 3;
    {PROTOBUF_FIELD_OFFSET(SceneReply, _impl_.positions_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Float3>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SceneReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SceneReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.meshids_.Clear();
  _impl_.positions_.Clear();
  _impl_.sceneid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SceneReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SceneReply& this_ = static_cast<const SceneReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SceneReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SceneReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SceneReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 sceneID = 1;
          if (this_._internal_sceneid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_sceneid(), target);
          }

          // repeated int32 meshIDs = 2;
          {
            int byte_size = this_._impl_._meshids_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  2, this_._internal_meshids(), byte_size, target);
            }
          }

          // repeated .Float3 positions = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_positions_size());
               i < n; i++) {
            const auto& repfield = this_._internal_positions().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SceneReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SceneReply::ByteSizeLong(const MessageLite& base) {
          const SceneReply& this_ = static_cast<const SceneReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SceneReply::ByteSizeLong() const {
          const SceneReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SceneReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 meshIDs = 2;
             {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_meshids())
              ;
              this_._impl_._meshids_cached_byte_size_.Set(
                  ::_pbi::ToCachedSize(data_size));
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
            // repeated .Float3 positions = 3;
             {
              total_size += 1UL * this_._internal_positions_size();
              for (const auto& msg : this_._internal_positions()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int32 sceneID = 1;
            if (this_._internal_sceneid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sceneid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SceneReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SceneReply*>(&to_msg);
  auto& from = static_cast<const SceneReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SceneReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_meshids()->MergeFrom(from._internal_meshids());
  _this->_internal_mutable_positions()->MergeFrom(
      from._internal_positions());
  if (from._internal_sceneid() != 0) {
    _this->_impl_.sceneid_ = from._impl_.sceneid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SceneReply::CopyFrom(const SceneReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SceneReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SceneReply::InternalSwap(SceneReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.meshids_.InternalSwap(&other->_impl_.meshids_);
  _impl_.positions_.InternalSwap(&other->_impl_.positions_);
        swap(_impl_.sceneid_, other->_impl_.sceneid_);
}

::google::protobuf::Metadata SceneReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Float3::_Internal {
 public:
};

Float3::Float3(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Float3)
}
Float3::Float3(
    ::google::protobuf::Arena* arena, const Float3& from)
    : Float3(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Float3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Float3::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Float3::~Float3() {
  // @@protoc_insertion_point(destructor:Float3)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Float3::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Float3::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Float3_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Float3::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Float3>(),
            ::google::protobuf::Message::GetNewImpl<Float3>(),
            ::google::protobuf::Message::GetClearImpl<Float3>(), &Float3::ByteSizeLong,
                &Float3::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Float3, _impl_._cached_size_),
            false,
        },
        &Float3::kDescriptorMethods,
        &descriptor_table_SceneLoad_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Float3::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Float3::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Float3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Float3::Clear() {
// @@protoc_insertion_point(message_clear_start:Float3)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Float3::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Float3& this_ = static_cast<const Float3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Float3::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Float3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Float3)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x(), target);
          }

          // float y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y(), target);
          }

          // float z = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Float3)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Float3::ByteSizeLong(const MessageLite& base) {
          const Float3& this_ = static_cast<const Float3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Float3::ByteSizeLong() const {
          const Float3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Float3)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
              total_size += 5;
            }
            // float y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
              total_size += 5;
            }
            // float z = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Float3::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Float3*>(&to_msg);
  auto& from = static_cast<const Float3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Float3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Float3::CopyFrom(const Float3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Float3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Float3::InternalSwap(Float3* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Float3, _impl_.z_)
      + sizeof(Float3::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Float3, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Float3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SceneLoad_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
